pipeline {
    agent any
    tools {
        nodejs 'Node18'
    }

    environment {
        DOCKER_IMAGE = "hannah213/mern-todo-app"
    }

    stages {

        // stage('Clone Repository') {
        //     steps {
        //         git 'https://github.com/YOUR_USERNAME/mern-todo-app.git'
        //     }
        // }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }

        stage('Login to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'USERNAME',
                    passwordVariable: 'PASSWORD'
                )]) {
                    sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $DOCKER_IMAGE'
            }
        }

    }
}